# Server Config
appium.server.url=http://127.0.0.1:4723/

# Device Config - Android
android.platform.name=Android
android.automation.name=UiAutomator2
android.device.name=Android Emulator
android.app.package=com.almuzaini.almuzaini
android.app.activity=com.almuzaini.almuzaini.MainActivity
android.app.wait.activity=*
android.no.reset=true
android.full.reset=false


# Device Config - iOS
ios.platform.name=iOS
ios.automation.name=XCUITest
ios.device.name=iPhone 15
ios.platform.version=17.0
ios.bundle.id=com.almuzaini.exchange
ios.udid=YOUR_UDID
ios.no.reset=false
ios.full.reset=false

# Environment Config
env.name=QA
base.url=https://qa-api.almuzaini.com
timeout.explicit=20
timeout.implicit=0
